#save as /etc/netplan/00-installer-config.yaml
# mark all other files as .old
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: no
      addresses: [192.168.1.76/24]
#      gateway4: 192.168.1.1
      routes:
       - to: default
         via: 192.168.1.1
      nameservers:
        addresses: [192.168.1.1,1.1.1.1]
